package cn.com.entity;

// Generated 2013-7-15 15:24:02 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", schema = "dbo", catalog = "jmrb")
public class TbUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5594996054521868054L;
	private String id;
	private String username;
	private String password;

	public TbUser() {
	}

	public TbUser(String id) {
		this.id = id;
	}

	public TbUser(String id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "username", length = 15)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
