package cn.com.pojo;

// Generated 2013-6-23 21:31:27 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsNews generated by hbm2java
 */
@Entity
@Table(name = "FS_News ", schema = "dbo", catalog = "jmrb")
public class FsNews implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7516617368858968794L;
	private long id;
	private String newsId;
	private String title;
	private String subTitle;
	private String classId;
	private short headNewsTf;
	private String headNewsPath;
	private String content;
	private Date addDate;
	private String keyWords;
	private String author;
	private String editer;
	private short picNewsTf;
	private String picPath;
	private short auditTf;

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NewsID", nullable = false)
	public String getNewsId() {
		return this.newsId;
	}

	public void setNewsId(String newsId) {
		this.newsId = newsId;
	}

	@Column(name = "Title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "SubTitle")
	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	@Column(name = "ClassID", nullable = false)
	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	@Column(name = "HeadNewsTF", nullable = false)
	public short getHeadNewsTf() {
		return this.headNewsTf;
	}

	public void setHeadNewsTf(short headNewsTf) {
		this.headNewsTf = headNewsTf;
	}

	@Column(name = "HeadNewsPath")
	public String getHeadNewsPath() {
		return this.headNewsPath;
	}

	public void setHeadNewsPath(String headNewsPath) {
		this.headNewsPath = headNewsPath;
	}

	@Column(name = "Content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AddDate", nullable = false, length = 23)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "KeyWords")
	public String getKeyWords() {
		return this.keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	@Column(name = "Author")
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "Editer")
	public String getEditer() {
		return this.editer;
	}

	public void setEditer(String editer) {
		this.editer = editer;
	}

	@Column(name = "PicNewsTF", nullable = false)
	public short getPicNewsTf() {
		return this.picNewsTf;
	}

	public void setPicNewsTf(short picNewsTf) {
		this.picNewsTf = picNewsTf;
	}

	@Column(name = "PicPath")
	public String getPicPath() {
		return this.picPath;
	}

	public void setPicPath(String picPath) {
		this.picPath = picPath;
	}

	@Column(name = "AuditTF", nullable = false)
	public short getAuditTf() {
		return this.auditTf;
	}

	public void setAuditTf(short auditTf) {
		this.auditTf = auditTf;
	}

}
